[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*.json"
  to = "/index.html"
  status = 200 